### ISSUE TITLE
我有一个朋友是四川的，他没有github账号，他让我问你一下这个主题的问题：

### ISSUE THREAD

**Issue by GHchenjingqi** [fordes123/ITEM#20]
1，换了这个主题后，首页不显示文章，必须重新编辑文章后首页才会显示，如何解决。
2，详情页有显示标签，但无法点击

**Comment by fordes123** [comment]
> 1，换了这个主题后，首页不显示文章，必须重新编辑文章后首页才会显示，如何解决。 2，详情页有显示标签，但无法点击

1. 直接切换主题，旧的文章缺少一些自定义字段所以不显示，这个问题没办法解决，建议全新安装比较好；或者直接对数据库进行修改
2. 没有做标签搜索，标签无法点击是正常情况
