### ISSUE TITLE
站在大佬肩膀上新增了一点，能合入master么

### ISSUE THREAD

**Issue by NotOrdinary** [fordes123/ITEM#24]
1.  支持站内搜索
2. 支持区分网址导航/小程序导航/文章
3. 支持详情页查看大图
4. 新增归档页面
演示：[艾迪导航](https://www.iddh.cn)

**Comment by fordes123** [comment]
可以的，欢迎提交 Pull requests

---
CDN 建议换一下，cdn.staticfile.net 可能存在投毒

**Comment by NotOrdinary** [comment]
> 可以的，欢迎提交 Pull requests
> 
> CDN 建议换一下，cdn.staticfile.net 可能存在投毒

哦哦，不知道这个有投毒，我换个

**Comment by fordes123** [comment]
感谢贡献，已经合并到 `main` 分支 #25

**Comment by fordes123** [comment]
为了保证对旧版数据的兼容，额外调整了一下文章类型枚举，资源文件也整合到了一起

**Comment by NotOrdinary** [comment]
> 为了保证对旧版数据的兼容，额外调整了一下文章类型枚举，资源文件也整合到了一起

谢谢大佬认可合入，再做小程序导航找了一圈喜欢这个主题，但是我想要的东西没有就自己随便加了，都是面向chatgpt编程的，代码写的不好，给你增加工作量了，哈哈哈
