### ISSUE TITLE
作者您好，是否考虑增加一个二级页面？

### ISSUE THREAD

**Issue by mybaiwan** [fordes123/ITEM#29]
如图，首页可以选择直接进入网址，默认情况下点击，进入二级页面？
![QQ截图20241113155304](https://github.com/user-attachments/assets/9890e941-3138-4a83-8741-2251a78bcf5f)

**Comment by mybaiwan** [comment]
![QQ截图20241113155525](https://github.com/user-attachments/assets/9993a127-e118-432c-9668-74a507123c91)

**Comment by fordes123** [comment]
已经有了，点击图标进入二级页面

**Comment by mybaiwan** [comment]
感谢解答
