### ISSUE TITLE
启用主题后发布文章，点击文章报错

### ISSUE THREAD

**Issue by CandyLeaves** [fordes123/ITEM#31]
撰写完站内文章后，设置文章类型为站内文章，跳转地址留空，简单介绍已经填写，图标URL和评分也以及填写，在前台首页点击文章发生错误，网站title显示500

syntax error, unexpected end of file, expecting "elseif" or "else" or "endif"

翻译如下：语法错误，意外的文件结尾，需要 “elseif” 或 “else” 或 “endif”

运行环境：
PHP8.2，MySQL8.0，typecho1.2.1

**Comment by fordes123** [comment]
无法复现。使用项目内的 docker-compose 配置并指定了依赖组件版本，可以正常创建/查看站内文章

1. 请问是否修改过源码
2. 能否提供更详细的错误信息

**Comment by CandyLeaves** [comment]
我并没有对源码进行任何修改，使用云服务器和1panel面板中的运行环境进行部署的，对于更详细的错误信息我也无法给出，因为我对这php和typecho模板方面并不是很了解

由于我的云服务器已经部署别的模板，所以我在vm虚拟机内使用XAMPP进行模拟，使用全新的typecho安装本模板
1. 设置文章类型为站内文章
2. 其余可留空的输入留空
3. 设置评分5.0
4. 发布文章

![image](https://github.com/user-attachments/assets/b8fc9ac4-d15c-45e2-a1bb-834d8993cd0e)
![image](https://github.com/user-attachments/assets/484fe2ca-7e8c-4641-aad0-8b785da8b1ca)


在网站首页可以显示文章，当我点击后会显示以下字样
![image](https://github.com/user-attachments/assets/52390367-0c6c-4010-b373-2ba8aef9fc64)
![image](https://github.com/user-attachments/assets/49232e68-e23e-4cd9-8dc8-8ca1a0a7a8e2)

**Comment by fordes123** [comment]
在 https://github.com/fordes123/ITEM/pull/34 中尝试对部分语法进行了调整，如果有空的话可以试试看问题是否解决

**Comment by CandyLeaves** [comment]
非常感谢您的努力，经过我的尝试我认为该问题已经解决。
![image](https://github.com/user-attachments/assets/b07efe82-b6ac-4c38-a170-cc67d29dddb4)
