### ISSUE TITLE
关于二级分类，以及链接出现在多个分类里面

### ISSUE THREAD

**Issue by imgecho** [fordes123/ITEM#8]
![微信图片_20240312160507](https://github.com/fordes123/ITEM/assets/42839331/db6b209e-361f-451d-b240-d2edba911128)
看上图，分类一个，却出现到所有里面
我有设置新的分类在游戏仓库里面，也会显示到所有里面
![企业微信截图_17102308101698](https://github.com/fordes123/ITEM/assets/42839331/99235701-c7bd-4f27-9727-4829069b6b68)
设置了二级分类，但是不显示在这里

**Comment by fordes123** [comment]
如下图尝试复现了一下：
![image](https://github.com/fordes123/ITEM/assets/52121395/d3b4e1f1-09ad-45a4-b806-a4bb95859859)

并没有出现文章重复和子分类不展示 
![image](https://github.com/fordes123/ITEM/assets/52121395/9b784cd7-862f-4848-bd39-db2f8a0f3e78)

---
建议尝试进行全新安装  
或者提供一下 typecho版本、php版本、mysql 版本以及数据库文件，我看是否能够复现问题

**Comment by imgecho** [comment]
![image](https://github.com/fordes123/ITEM/assets/42839331/cfddce68-5ffe-4d36-801f-12fd232e8694)
docker安装的，我改成LNMP试一下

**Comment by zuji365** [comment]
我的也出现同样的问题
typecho版本1.3.0、php版本8.0、mysql版本5.6.51
[数据库.zip](https://github.com/fordes123/ITEM/files/14734239/default.zip)

**Comment by fordes123** [comment]
> 我的也出现同样的问题 typecho版本1.3.0、php版本8.0、mysql版本5.6.51 [数据库.zip](https://github.com/fordes123/ITEM/files/14734239/default.zip)

这个问题应该在 https://github.com/fordes123/ITEM/releases/tag/v1.0.2 得到解决

**Comment by zuji365** [comment]
老师好，我又试了下，好像还是不得行，还是重复发自我的华为手机-------- 原始邮件 --------发件人： 以谶 ***@***.***>日期： 2024年3月26日周二 15:30收件人： fordes123/ITEM ***@***.***>抄送： zuji365 ***@***.***>, Comment ***@***.***>主    题： Re: [fordes123/ITEM] 关于二级分类，以及链接出现在多个分类里面 (Issue #8)

我的也出现同样的问题 typecho版本1.3.0、php版本8.0、mysql版本5.6.51 数据库.zip

这个问题应该在 https://github.com/fordes123/ITEM/releases/tag/v1.0.2 得到解决

**Comment by fordes123** [comment]
> 老师好，我又试了下，好像还是不得行，还是重复发自我的华为手机-------- 原始邮件 --------发件人： 以谶 ***@***.***>日期： 2024年3月26日周二 15:30收件人： fordes123/ITEM ***@***.***>抄送： zuji365 ***@***.***>, Comment ***@***.***>主 题： Re: [fordes123/ITEM] 关于二级分类，以及链接出现在多个分类里面 (Issue #8) 我的也出现同样的问题 typecho版本1.3.0、php版本8.0、mysql版本5.6.51 数据库.zip 这个问题应该在 https://github.com/fordes123/ITEM/releases/tag/v1.0.2 得到解决 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

在我这边验证确实无法复现，`mysql:5.6.51`、`php:8.0.0-fpm-alpine`、`typecho-v1.3.0-alpha`、`ITEM-v1.0.2`，导入你提供的数据库文件，进入首页并没有发现错误：  
![](https://github.com/fordes123/ITEM/assets/52121395/f5e6677f-07aa-4561-a5e8-af693e9da271)
